### ISSUE TITLE
Running the code on Heroku display an error

### ISSUE THREAD

**Issue by cuesto** [marcosfermin/pencilcrunch#1]
https://pencilcrunch.herokuapp.com

Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 500

**Comment by marcosfermin** [comment]
@cuesto Can you copy and paste the content in the file in the /core/CodeIgniter.php ?

**Comment by marcosfermin** [comment]
@cuesto Have you made any changes to /system/core/CodeIgniter.php so far?

**Comment by jblandino** [comment]
Hey @cuesto  and @marcosfermin
This is due to the credentials in [application/config/database.php](https://github.com/marcosfermin/pencilcrunch/blob/master/application/config/database.php) usually when you are using a provider as heroku you should use the connection socket.

If the server is something like xampp, mamp or lamp should work properly.
